<?php

return [
    // Public URL to a signed update manifest generated by the external release tool.
    // If you use github_repository below, you can leave this empty.
    'manifest_url' => '',

    // Public repository with signed builds, for example: your-org/prestashopinventory-builds
    'github_repository' => 'hejsiri/prestashopinventory-builds',

    // Branch in the public builds repository.
    'github_branch' => 'main',

    // Path to the signed manifest inside the public builds repository.
    'manifest_path' => 'latest.json',
];
